// Boundary rules for crate dependencies and lightweight profiles.

const agentRuntimeIpcForbiddenDeps = [
  'halo-acp',
  'halo-agent-runtime',
  'halo-agent-stream',
  'halo-agent-tools',
  'halo-ai-adapters',
  'halo-claude-code-adapter',
  'halo-codex-adapter',
  'halo-core',
  'halo-core-types',
  'halo-external-sources',
  'halo-harness',
  'halo-opencode-adapter',
  'halo-page-function-runtime',
  'halo-plugin-runtime-client',
  'halo-product-capabilities',
  'halo-relay-service',
  'halo-runtime-services',
  'halo-sdk-host',
  'halo-services-core',
  'halo-services-integrations',
  'halo-static-hook-support',
  'halo-tool-call-jsonrepair',
  'halo-tool-packs',
  'halo-transport',
  'halo-webdriver',
  'terminal-core',
  'tool-runtime',
  'tauri',
  'reqwest',
  'tokio-tungstenite',
  'halo-cli',
  'ratatui',
  'crossterm',
  'arboard',
  'syntect-tui',
];

const piRpcAdapterForbiddenDeps = [
  'halo-acp',
  'halo-agent-runtime',
  'halo-agent-runtime-ipc',
  'halo-agent-stream',
  'halo-agent-tools',
  'halo-ai-adapters',
  'halo-claude-code-adapter',
  'halo-codex-adapter',
  'halo-core',
  'halo-external-sources',
  'halo-harness',
  'halo-opencode-adapter',
  'halo-plugin-runtime-client',
  'halo-product-capabilities',
  'halo-runtime-services',
  'halo-sdk-host',
  'halo-static-hook-support',
  'halo-tool-packs',
  'halo-cli',
  'ratatui',
  'crossterm',
  'arboard',
  'syntect-tui',
  'tauri',
  'tool-runtime',
];

export const noCoreDependencyCrates = [
  'core-types',
  'events',
  'ai-adapters',
  'agent-stream',
  'tool-call-jsonrepair',
  'agent-runtime',
  'agent-runtime-ipc',
  'harness',
  'plugin-runtime-client',
  'product-capabilities',
  'runtime-ports',
  'runtime-services',
  'sdk-host',
  'services-core',
  'services-integrations',
  'agent-tools',
  'tool-packs',
  'product-domains',
  'claude-code-adapter',
  'codex-adapter',
  'opencode-adapter',
  'pi-rpc-adapter',
  'static-hook-support',
  'external-sources',
  'terminal',
  'tool-runtime',
  'transport',
  'webdriver',
];

export const forbiddenManifestDependencyRules = [
  {
    dependencyNames: ['halo-agent-runtime-ipc'],
    scanRoots: ['src/apps', 'src/crates', 'Halo-Installer/src-tauri'],
    workspaceManifestPath: 'Cargo.toml',
    allowManifestPaths: ['src/apps/cli/Cargo.toml'],
    reason: 'the private local IPC protocol has one reviewed first-party Shared TUI consumer',
    message:
      'agent-runtime-ipc may only be consumed by the CLI Shared TUI adapter; SDK Host, GUI, remote, and other products require separate review',
  },
  {
    dependencyNames: ['sherpa-onnx'],
    scanRoots: ['src/apps', 'src/crates', 'Halo-Installer/src-tauri'],
    forbidWorkspaceAliases: false,
    allowManifestPaths: [
      'src/crates/services/services-integrations/Cargo.toml',
    ],
    reason:
      'speech recognition engines are concrete integration service dependencies',
    message:
      'sherpa-onnx must stay in services-integrations and be injected by a product composition root',
  },
  {
    dependencyNames: ['halo-opencode-adapter'],
    scanRoots: ['src/apps', 'src/crates', 'Halo-Installer/src-tauri'],
    workspaceManifestPath: 'Cargo.toml',
    allowManifestPaths: [
      'src/crates/adapters/opencode-adapter/Cargo.toml',
      'src/crates/assembly/core/Cargo.toml',
    ],
    reason:
      'OpenCode adapter production dependencies are limited to the reviewed product composition root',
    message:
      'only halo-core product-full assembly may register halo-opencode-adapter through reviewed capability composition roots',
  },
  {
    dependencyNames: ['halo-pi-rpc-adapter'],
    scanRoots: ['src/apps', 'src/crates', 'Halo-Installer/src-tauri'],
    workspaceManifestPath: 'Cargo.toml',
    allowManifestPaths: ['src/crates/assembly/core/Cargo.toml'],
    reason:
      'the P0 Pi RPC execution adapter has one reviewed Halo Workbench product composition root',
    message:
      'only halo-core Halo Workbench product assembly may select halo-pi-rpc-adapter; apps, contracts, execution owners, and sibling adapters consume the Workbench seam instead',
  },
  ...[
    ['halo-claude-code-adapter', 'claude-code-adapter'],
    ['halo-codex-adapter', 'codex-adapter'],
  ].map(([dependencyName, crateName]) => ({
    dependencyNames: [dependencyName],
    scanRoots: ['src/apps', 'src/crates', 'Halo-Installer/src-tauri'],
    workspaceManifestPath: 'Cargo.toml',
    allowManifestPaths: [
      `src/crates/adapters/${crateName}/Cargo.toml`,
      'src/crates/assembly/core/Cargo.toml',
    ],
    reason: `${crateName} production dependencies are limited to the reviewed product composition root`,
    message: `only halo-core product-full assembly may register ${dependencyName} through the static Hook provider boundary`,
  })),
  {
    dependencyNames: ['halo-static-hook-support'],
    scanRoots: ['src/apps', 'src/crates', 'Halo-Installer/src-tauri'],
    workspaceManifestPath: 'Cargo.toml',
    allowManifestPaths: [
      'src/crates/adapters/static-hook-support/Cargo.toml',
      'src/crates/adapters/opencode-adapter/Cargo.toml',
      'src/crates/adapters/claude-code-adapter/Cargo.toml',
      'src/crates/adapters/codex-adapter/Cargo.toml',
    ],
    reason: 'static Hook parsing support is private to ecosystem source adapters',
    message: 'static Hook support may only be consumed by reviewed ecosystem Hook adapters',
  },
];

export const lightweightBoundaryRules = [
  {
    crateName: 'agent-runtime-ipc',
    reason:
      'agent-runtime-ipc is the non-published local protocol for the reviewed Shared TUI adapter, not a Runtime, SDK Host, service, or remote product surface',
    forbiddenDeps: agentRuntimeIpcForbiddenDeps,
  },
  {
    crateName: 'pi-rpc-adapter',
    reason:
      'pi-rpc-adapter is the Pi RPC projection for the Halo Workbench execution seam, not a runtime owner, product selector, ACP path, or generic executor registry',
    forbiddenDeps: piRpcAdapterForbiddenDeps,
  },
  {
    crateName: 'core-types',
    reason: 'core-types must stay low-level DTO-only',
    forbiddenDeps: [
      'halo-core',
      'halo-events',
      'halo-ai-adapters',
      'halo-agent-stream',
      'halo-runtime-ports',
      'halo-services-core',
      'halo-services-integrations',
      'halo-agent-tools',
      'halo-tool-packs',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'runtime-ports',
    reason: 'runtime-ports must stay DTO/trait-only',
    forbiddenDeps: [
      'halo-core',
      'halo-agent-stream',
      'halo-services-core',
      'halo-services-integrations',
      'halo-agent-tools',
      'halo-tool-packs',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'runtime-services',
    reason: 'runtime-services must stay a typed service assembly contract without concrete runtime implementations',
    forbiddenDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-agent-stream',
      'halo-services-core',
      'halo-services-integrations',
      'halo-agent-tools',
      'halo-tool-packs',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'agent-runtime',
    reason: 'agent-runtime must own portable runtime decisions without concrete service or product implementations',
    forbiddenDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-services-core',
      'halo-services-integrations',
      'halo-tool-packs',
      'halo-product-capabilities',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'sdk-host',
    reason:
      'SDK Host protocol must stay a portable Runtime adapter without concrete product, terminal, service, or CLI implementations',
    forbiddenDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-services-core',
      'halo-services-integrations',
      'halo-agent-tools',
      'halo-tool-packs',
      'halo-product-capabilities',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-sdk-host-app',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'harness',
    reason:
      'harness must own workflow contracts without concrete service, product, or platform implementations',
    forbiddenDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-services-core',
      'halo-services-integrations',
      'halo-tool-packs',
      'halo-product-capabilities',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'plugin-runtime-client',
    reason:
      'plugin-runtime-client must implement the portable PluginRuntimeClient boundary without concrete ecosystem, product, or platform implementations',
    forbiddenDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-opencode-adapter',
      'halo-services-core',
      'halo-services-integrations',
      'halo-agent-tools',
      'halo-tool-packs',
      'halo-product-capabilities',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'product-capabilities',
    reason:
      'product-capabilities must own product capability assembly facts without concrete runtime implementations',
    forbiddenDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-agent-tools',
      'halo-services-core',
      'halo-services-integrations',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'agent-tools',
    reason: 'agent-tools must not depend on concrete service or product runtime implementations',
    forbiddenDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-services-core',
      'halo-services-integrations',
      'halo-tool-packs',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
];

export const dependencyProfileRules = [
  {
    crateName: 'agent-runtime-ipc',
    profileName: 'private Shared TUI local IPC profile',
    reason:
      'agent-runtime-ipc may share stable event and Runtime DTO contracts but must not acquire Runtime owners, SDK Host, services, remote transports, or product implementations',
    forbiddenNonOptionalDeps: agentRuntimeIpcForbiddenDeps,
  },
  {
    crateName: 'core',
    profileName: 'no-default runtime-surface-light profile',
    reason:
      'halo-core no-default profile must not force product/runtime integration dependencies',
    forbiddenNonOptionalDeps: [
      'aes',
      'aes-gcm',
      'halo-product-capabilities',
      'halo-product-domains',
      'halo-relay-service',
      'halo-tool-packs',
      'chrono-tz',
      'cron',
      'dashmap',
      'eventsource-stream',
      'filetime',
      'flate2',
      'fs2',
      'git2',
      'glob',
      'globset',
      'hostname',
      'htmd',
      'image',
      'include_dir',
      'indexmap',
      'legible',
      'local-ip-address',
      'mac_address',
      'md5',
      'qrcode',
      'rand',
      'readability-js',
      'rmcp',
      'russh',
      'sse-stream',
      'similar',
      'tool-runtime',
      'tokio-tungstenite',
      'x25519-dalek',
    ],
  },
  {
    crateName: 'core-types',
    profileName: 'default DTO profile',
    reason: 'core-types default profile must stay DTO-only',
    forbiddenNonOptionalDeps: [
      'halo-core',
      'halo-events',
      'halo-ai-adapters',
      'halo-agent-stream',
      'halo-runtime-ports',
      'halo-services-core',
      'halo-services-integrations',
      'halo-agent-tools',
      'halo-tool-packs',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'runtime-ports',
    profileName: 'default ports profile',
    reason: 'runtime-ports default profile must stay trait/DTO-only',
    forbiddenNonOptionalDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-agent-stream',
      'halo-services-core',
      'halo-services-integrations',
      'halo-agent-tools',
      'halo-tool-packs',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'runtime-services',
    profileName: 'default runtime service assembly profile',
    reason: 'runtime-services default profile must not compile concrete service or product runtime implementations',
    forbiddenNonOptionalDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-agent-stream',
      'halo-services-core',
      'halo-services-integrations',
      'halo-agent-tools',
      'halo-tool-packs',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'agent-runtime',
    profileName: 'default agent runtime decision profile',
    reason: 'agent-runtime default profile must not compile concrete services or product surfaces',
    forbiddenNonOptionalDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-services-core',
      'halo-services-integrations',
      'halo-tool-packs',
      'halo-product-capabilities',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'plugin-runtime-client',
    profileName: 'default plugin runtime client boundary profile',
    reason:
      'plugin-runtime-client default profile must not compile concrete plugin execution or product-surface implementations',
    forbiddenNonOptionalDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-opencode-adapter',
      'halo-services-core',
      'halo-services-integrations',
      'halo-agent-tools',
      'halo-tool-packs',
      'halo-product-capabilities',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'agent-tools',
    profileName: 'tool contract-only profile',
    reason: 'agent-tools must stay a lightweight tool contract crate',
    forbiddenNonOptionalDeps: [
      'halo-ai-adapters',
      'halo-product-capabilities',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'tauri',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'product-capabilities',
    profileName: 'default product capability profile',
    reason: 'product-capabilities default profile must stay assembly-fact only',
    forbiddenNonOptionalDeps: [
      'halo-core',
      'halo-ai-adapters',
      'halo-agent-tools',
      'halo-services-core',
      'halo-services-integrations',
      'halo-product-domains',
      'halo-transport',
      'terminal-core',
      'tool-runtime',
      'tauri',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'product-domains',
    profileName: 'default product domain profile',
    reason: 'product-domains default profile must not compile runtime/platform helpers',
    forbiddenNonOptionalDeps: [
      'dirs',
      'log',
      'sha2',
      'which',
      'reqwest',
      'git2',
      'rmcp',
      'image',
      'tokio-tungstenite',
      'tauri',
      'halo-cli',
      'ratatui',
      'crossterm',
      'arboard',
      'syntect-tui',
    ],
  },
  {
    crateName: 'services-integrations',
    profileName: 'default integrations profile',
    reason: 'services-integrations default profile must not compile feature-gated integrations',
    forbiddenNonOptionalDeps: [
      'aes',
      'aes-gcm',
      'anyhow',
      'async-trait',
      'base64',
      'halo-product-domains',
      'halo-runtime-ports',
      'halo-services-core',
      'chrono',
      'dunce',
      'futures',
      'git2',
      'hex',
      'local-ip-address',
      'md5',
      'notify',
      'rand',
      'reqwest',
      'rmcp',
      'sha2',
      'sse-stream',
      'thiserror',
      'tokio-util',
      'tokio-tungstenite',
      'uuid',
      'which',
    ],
  },
];


