[package]
name = "halo-tauri-desktop"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Halo Studio local coding workbench (Tauri)"

[[bin]]
name = "halo-studio"
path = "src/main.rs"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true

[features]
default = []
devtools = ["tauri/devtools"]
